### PR TITLE
Support DPUB to send deferred messages

### PR DESCRIPTION
**Pull request by Soulou**

### CODE REVIEW

**Comment by bschwartz** [comment]
Hi Soulou! Thanks for the PR! It looks great, and thanks for updating the README too. A few questions:

What do you think about making `deferred_write` take the number of seconds to defer rather than a time? That feels like it will be more in line with how it is in NSQ and how it is in the reference client implementations:

- https://github.com/nsqio/go-nsq/pull/139
- https://github.com/nsqio/pynsq/pull/140

Also, should it take seconds or milliseconds as its argument? Feeling divided on that. Seconds seems more Ruby-esque I suppose.

Any thoughts @freerobby?

**Comment by bschwartz** [comment]
@Soulou any thoughts on using seconds as an arg instead of a time for `deferred_write`? And thoughts on using seconds instead of milliseconds to be more ruby-like (e.g. `sleep` takes a time in seconds)?

**Comment by Soulou** [comment]
I agree that seconds sounds much more ruby-esque as you can do `Time.now + 1` which means + 1 sec by default.

No problem to edit the README, sorry for the delay between the PR and my reaction :-)

**Comment by Soulou** [comment]
We could use sidekiq model and using a float (which is multiplied by 1000 before sending the command)

As a result, both would work:

```
deferred_write(1, ...)
deferred_write(10.124, ...)
```

**Comment by bschwartz** [comment]
Love the float idea. Good thinking!

**Comment by Soulou** [comment]
Ok I'll handle it when I've a few minutes :)

**Comment by Soulou** [comment]
Done !

**Comment by bschwartz** [comment]
Thanks @Soulou. Looks good to me! Going to merge this, bump the version, and publish to ruby gems.
Also adding you as a contributor ;)

**Comment by freerobby** [comment]
Sorry I'm late to the party on this! Thanks @Soulou for contributing here, agree with both of you that seconds works nicely for the ruby client!

**Comment by bschwartz** [comment]
Bumped to 1.7.0 and released on Rubygems. Thanks again for this @Soulou!

**Pull request merged**
